Fix bug where Sec-WebSocket-Protocol header was required in handshake…
novnc/websockify-other pull request #11
Opened 2020-08-13 12:18 UTC by frpermab

… even if no protocols were given

2020-09-04 07:35 UTC, CendioOssman requested changes

2020-09-04 07:35 UTC, CendioOssman commented on c/websocket.c
> +        if(strlen(headers->protocols)) {
This looks incorrect. This function is supposed to fill out `headers->protocol`, so it doesn't have a sane value before this. So we can't look at it.

2020-09-04 07:35 UTC, CendioOssman commented on c/websocket.c
> +        if (!response_protocol) {
You probably need to handle the empty string here as well.

2020-09-04 08:19 UTC, frpermab commented on c/websocket.c
> +        if(strlen(headers->protocols)) {
In fact, headers->protocols is populated at the top of the function, in this line:

headers_t *headers = ws_ctx->headers;

So we *can* look at that field here.

2020-09-04 08:22 UTC, frpermab commented on c/websocket.c
> +        if(strlen(headers->protocols)) {
Sorry, I should not appear so confident. I *think* this is how it works...

2020-09-04 11:16 UTC, CendioOssman commented on c/websocket.c
> +        if(strlen(headers->protocols)) {
That only sets `headers`, but not any field within it. If you look at the file you'll see that there is only a single place where `protocols` is assigned any value, and that is the line `strncpy(headers->protocols, start, end-start);`.  So I'm afraid your check cannot look at its value before that.

2020-09-04 11:18 UTC, frpermab commented on c/websocket.c
> +        if(strlen(headers->protocols)) {
I see. I have made a mistake. I will try to come up with a solution that works properly. Thanks.

2020-10-21 10:41 UTC, CendioOssman commented
Closed in favour of #12.

2020-10-21 10:41 UTC, closed without merging