Add CMakeList.txt, allow TLS1.x and remove trailing spaces
novnc/websockify-other pull request #15
Opened 2021-03-29 12:06 UTC by clementperon

Quick simple but fix the following warning:

```c
websocket.c: In function ‘ws_socket_ssl’:
websocket.c:160:5: warning: ‘TLSv1_server_method’ is deprecated [-Wdeprecated-declarations]
  160 |     ctx->ssl_ctx = SSL_CTX_new(TLSv1_server_method());
      |     ^~~
In file included from /usr/include/openssl/e_os2.h:13,
                 from /usr/include/openssl/err.h:13,
                 from websocket.c:23:
/usr/include/openssl/ssl.h:1878:1: note: declared here
 1878 | DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_server_method(void))
      | ^~~~~~~~~~~~~~~~~~
```

2021-03-30 08:42 UTC, clementperon commented
Add a fix for #16

2021-04-01 13:42 UTC, clementperon commented
@CendioOssman could you review this PR, please I will be happy to make some changes if needed.

2021-04-20 09:44 UTC, clementperon commented
Maybe @larsbrinkhoff could you review this PR? Thanks :)

2021-04-25 11:18 UTC, larsbrinkhoff commented
Sorry, I'm a bit pressed for time.

2021-05-02 12:06 UTC, ZReC approved these changes

2021-05-03 12:16 UTC, CendioOssman requested changes

2021-05-03 12:16 UTC, CendioOssman commented on c/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.12)
We already have a `Makefile`, so this would conflict with that. What issue does adding CMake solve? It's a bit overkill for a small project like this.

2021-05-03 12:16 UTC, CendioOssman commented on c/websocket.c
> +    ctx->ssl_ctx = SSL_CTX_new(TLS_server_method());
This potentially also allows SSLv3, but it's what OpenSSL recommends so I guess this is good.

2021-05-03 12:16 UTC, CendioOssman commented on c/websocket.c
>          start = strstr(handshake, "\r\nSec-WebSocket-Origin: ");
This seems to have been dropped from final RFC. Perhaps just completely nuke this code?

2021-05-03 12:24 UTC, clementperon commented on c/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.12)
Quicker to add the install target.

2021-05-03 12:25 UTC, clementperon commented on c/websocket.c
> +    ctx->ssl_ctx = SSL_CTX_new(TLS_server_method());
yes you're right on this, maybe i can update the commit title to reflect this

2021-05-03 12:28 UTC, clementperon commented on c/websocket.c
>          start = strstr(handshake, "\r\nSec-WebSocket-Origin: ");
I used wscat for my test and you can still specify the origin. Up to you, IMO the code is not so complicated to keep the compatibility.

2021-05-03 12:39 UTC, CendioOssman commented on c/websocket.c
>          start = strstr(handshake, "\r\nSec-WebSocket-Origin: ");
Perhaps. But non-standard things should not really be in the wild. So if we're touching this code my vote is to get it in compliance with the RFC. I.e. remove it.

2021-05-03 13:02 UTC, clementperon commented on c/websocket.c
>          start = strstr(handshake, "\r\nSec-WebSocket-Origin: ");
ok

2021-05-03 13:03 UTC, clementperon commented on c/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.12)
I will drop this commit on keep this on on my fork.

2021-05-03 13:11 UTC, clementperon commented on c/websocket.c
>          start = strstr(handshake, "\r\nSec-WebSocket-Origin: ");
I have dropped the Sec-WebSocket-Origin

2021-05-03 13:48 UTC, CendioOssman approved these changes
Great, thanks!

2021-05-03 13:48 UTC, merged